from flask import render_template, session, redirect, request
from models import User, Section, SystemProperty
from Feather import app

#: DO NOT EDIT THIS FILE
#: This file contains all admin routes
#: You may break things

site = {
	'css': {
		'header': ['style.css'],
		'footer': []
	},
	'js': {
		'header': [],
		'footer': []
	}
}

#: useful render function
def render(template, title = "", args = None):
	return render_template(template,
		error = request.args.get('e'),
		success = request.args.get('s'),
		title = title,
		sysname = SystemProperty.get('name'),
		site = site,
		args = args)

#: Admin root level redirect
@app.route('/admin/')
@app.route('/admin/<page>/')
def admin_reroute(page = False):
	return redirect('/admin/dashboard')

#: Login
@app.route('/admin/login/')
def admin_login():
	if User.is_logged_in():
		return redirect('/admin/dashboard/')
	return render('admin/login.html', 'Login')

#: Dashboard
@app.route('/admin/dashboard/')
def admin_dashboard():
	if not User.is_logged_in():
		return redirect('/admin/login?e=You%20need%20to%20log%20in%20first')
	return render('admin/dashboard.html','Dashboard')

#: Sections
@app.route('/admin/sections/')
def admin_sections():
	if not User.is_logged_in():
		return redirect('/admin/login?e=You%20need%20to%20log%20in%20first')
	args = {
		'sections': Section.get_all()
	}
	return render('/admin/sections.html', 'Sections', args)

#: create a new section
@app.route('/admin/create/section')
def admin_create_section():
	if not User.is_logged_in():
		return redirect('/admin/login?e=You%20need%20to%20log%20in%20first')
	return render('/admin/section_single.html', 'Create new section')


#: Individual sections
@app.route('/admin/sections/<name>/')
def admin_sections_name(name):
	if not User.is_logged_in():
		return redirect('/admin/login?e=You%20need%20to%20log%20in%20first')
	args = {
		'section': Section.get(name)
	}
	return render('/admin/section_single.html', '{} section'.format(args['section'].title), args)

#: Users
@app.route('/admin/users/')
def admin_users():
	pass

#: System
@app.route('/admin/system/')
def admin_system():
	if not User.is_logged_in():
		return redirect('/admin/login?e=You%20need%20to%20log%20in%20first')
	args = {
		'mailchimp': {
			'list_id': SystemProperty.get('mc_list_id'),
			'api_key': SystemProperty.get('mc_api_key')
		},
		'custom_props': SystemProperty.get_custom_properties()
	}
	return render('admin/system.html','System', args)
